version: "2"

services:
  web:
    image: malte311/fly-scraper:latest
    #build:
    #  context: .
    container_name: fly-scraper
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - ./data/:/php-code/data/
      #- ./index.php:/php-code/index.php
      #- ./action.php:/php-code/action.php
      #- ./client/:/php-code/client/
    restart: always
    environment:
      - SERVERURL=https://example.com/fly-scraper